### ISSUE TITLE
38妇女节活动~不知道大佬有么有兴趣搞个脚本

### ISSUE THREAD

**Issue by z2kk77** [i-chenzhe/qx#11]
1.0复制整段话 https://JCuiErkGVkW43G集鞭炮赢京豆，百万京豆等你拿！#2Frz7AqB6a%→去猄倲← 
具体入口不清楚-。-其他群分享的。
任务和集鞭炮很像，有15 35 50，3个档次换豆子

**Comment by i-chenzhe** [comment]
lxk已经出了这个脚本了。
