### ISSUE TITLE
跳一跳

### ISSUE THREAD

**Issue by qaz88q11** [i-chenzhe/qx#13]
跳一跳不能用，望大佬修复

**Comment by i-chenzhe** [comment]
不能用麻烦上传截图。
或者tg群里找我。
你这一句不能用我不知道出什么问题了，我自己这边是可以用的呢。

qaz88q11 <notifications@github.com>于2021年3月2日 周二下午4:11写道：

**Comment by qaz88q11** [comment]
能用不好意思大佬，更新了下发现拉取的还是失效的js，后来鼓捣一下就好了拉取到最新的js

**Comment by i-chenzhe** [comment]
> 能用不好意思大佬，更新了下发现拉取的还是失效的js，后来鼓捣一下就好了拉取到最新的js

尽量别用CDN链接拉取
