### ISSUE TITLE
大佬，你的脚本能不能都带上个活动入口……

### ISSUE THREAD

**Issue by qq34347476** [i-chenzhe/qx#4]
找不到你的脚本里的活动入口页，能不能活动带上入口在注释……还有 walmart这个活动是下架了吗？

**Comment by i-chenzhe** [comment]
哪个活动的地址找不到？
Walmart已经被 粉丝互动 替代了。因为这个是一个系列活动，只要是这个系列的活动可以通用一个脚本。

Jiang <notifications@github.com>于2021年2月22日 周一下午8:01写道：

**Comment by qq34347476** [comment]
那新增的这个华硕爱奇艺活动入口在哪啊……

**Comment by i-chenzhe** [comment]
忘记写了。
https://asusiqiyi.m.jd.com

Jiang <notifications@github.com>于2021年2月22日 周一下午8:07写道：

**Comment by qq34347476** [comment]
那node端也没法参加互助活动嘛……能不能给个互助吗的变量啥的，自己填也行

**Comment by i-chenzhe** [comment]
什么活动需要增加互助码？

Jiang <notifications@github.com>于2021年2月22日 周一下午8:15写道：

**Comment by qq34347476** [comment]
比如还是这新增的华硕的……
再来个题外话，
大佬能不能授人以鱼不如授人以渔～
我也是前端能不能来个带入门～

**Comment by qq34347476** [comment]
比如还是这新增的华硕的……
再来个题外话，
大佬能不能授人以鱼不如授人以渔～
我也是前端能不能来个带入门～

**Comment by i-chenzhe** [comment]
增加环境变量这个事怎么说，我也不太懂node的环境所以我也不懂怎么增加环境变量，有空再研究研究。
如果你是前端的话，应该看得懂脚本的流程，其实就是抓包分析正常的手机端操作流程，然后把必要的参数抓取出来然后通过js脚本来模拟实现这些网络请求。

**Comment by qq34347476** [comment]
看的懂啊，关键是，不知道咋抓这个……我主要写pc的……能不能加个联系，不懂我请教你

**Comment by i-chenzhe** [comment]
> 看的懂啊，关键是，不知道咋抓这个……我主要写pc的……能不能加个联系，不懂我请教你

tg：zhe_8886
