### ISSUE TITLE
京东小魔方, 失败! 原因: TypeError: Cannot read property 'taskList' of undefined!

### ISSUE THREAD

**Issue by hclasmn** [i-chenzhe/qx#4]
![image](https://user-images.githubusercontent.com/32213103/111025935-6ef16380-8422-11eb-8a7f-5e407ca08fd6.png)

**Comment by i-chenzhe** [comment]
@hclasmn 非活动时间运行肯定是失败的。

**Comment by hclasmn** [comment]
搜嘎
