### ISSUE TITLE
大佬辛苦了！美丽研究院问题

### ISSUE THREAD

**Issue by kira0623** [i-chenzhe/qx#6]
获取基础信息成功
当前账户金币4000
当前账户等级2

获取背包信息成功
获取商品及店铺列表成功

获取福利列表成功
然按后就没了...每个帐号只能兑换豆子但是不做任务！大佬辛苦

**Comment by i-chenzhe** [comment]
按照默认cron，0点运行领取豆子，豆子超过10个才会发送通知，白天还会分别在9点、13点、20点运行。这个时候才会做任务，这个时候如果有获取奖励但豆子数量没有达到或超过10个，默认是静默运行不发送通知的。

kira0623 <notifications@github.com>于2021年2月25日 周四上午12:26写道：
