### ISSUE TITLE
大佬帮忙看下百变大咖秀，一直是出错的

### ISSUE THREAD

**Issue by shenhuash** [i-chenzhe/qx#9]
******开始【京东账号1】jd_138170nme*********                                                                                用户【jd_138170nme】信息获取成功                                                                                            ❗️百变大咖秀, 错误!                                           TypeError: Cannot read property 'settings' of undefined           at /storage/emulated/0/jd/scripts/entertainment.js:189:35     at got.post.then.message (/storage/emulated/0/jd/scripts/entertainment.js:573:6792)                                         at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                     活动已结束！                                                                                                                ❌ 百变大咖秀, 失败! 原因: TypeError: Cannot read property 'length' of undefined!

**Comment by i-chenzhe** [comment]
> ******开始【京东账号1】jd_138170nme*********                                                                                用户【jd_138170nme】信息获取成功                                                                                            ❗️百变大咖秀, 错误!                                           TypeError: Cannot read property 'settings' of undefined           at /storage/emulated/0/jd/scripts/entertainment.js:189:35     at got.post.then.message (/storage/emulated/0/jd/scripts/entertainment.js:573:6792)                                         at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                     活动已结束！                                                                                                                ❌ 百变大咖秀, 失败! 原因: TypeError: Cannot read property 'length' of undefined!

测试过正常的，你更新脚本试一下。
